config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :budgets
  resources :categories
  resources :periods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
    belongs_to :user
    belongs_to :category

    validates :period, presence: true

    def available(budget)
        budget.budgeted_value - budget.actual_value
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :budgets

    validates :category_name, :presence => true, :uniqueness => true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :budget
    belongs_to :period
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :budgets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
    before_action :set_budget, only: [:edit, :update, :destroy]
    def index
        @budgets = Budget.all.sort_by { |b| b.created_at }
        @transactions = Transaction.all
    end

    def new
        @budget = Budget.new
        @categories = Category.all
    end

    def create
        @budget = Budget.new(budget_params)
        @budget.user_id = current_user.id
        if @budget.save
            redirect_to budgets_path
        else
            render :new
        end
    end

    def edit
        @categories = Category.all
    end

    def update
        if @budget.update(budget_params)
            redirect_to budgets_path
        else
            render :edit
        end
    end
    
    def destroy
        @budget.destroy
        redirect_to budgets_path
    end


    private

    def set_budget
        @budget = Budget.find(params[:id])
    end

    def budget_params
        params.require(:budget).permit(:budgeted_value, :period, :actual_value, :category_id)
    end
        
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to budgets_path
        else
            render :new
    end 
    end 

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
        redirect_to budgets_path
    end

    # def self.empty?
    #     @categories = Category.all
    #     if @categories.empty?
    #     end
    # end
    private 

    def category_params 
        params.require(:category).permit(:category_name)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
    def create
    end
    
    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/budgets/_form.html.erb
<%= simple_form_for @budget do |f| %>
  <%= f.input :budgeted_value %>
  <% unless @categories.empty? %>
     <%= f.select :category_id, Category.all.collect { |c| [ c.category_name, c.id ] }, include_blank: true %>
  <% end %>
  <% if current_page?(new_budget_path) %> 
    <%= link_to 'Add a category', new_category_path %>
  <% end %>
  <%= f.input :actual_value %>
  <%= f.input :period %>
  <%= f.button :submit %>
<% end %>

app/views/budgets/edit.html.erb
<%= render 'budgets/form'%>

app/views/budgets/index.html.erb
<h1>Budgets</h1>

<table>
    <tr>
        <th>Category</th>
        <th>Budgeted</th>
        <th>Actual</th>
        <th>Available</th>
        <th></th>
    </tr>

    <% @budgets.each do |budget| %>
        <tr>
            <td><%= budget.category.category_name %></td>
            <td><%= link_to budget.budgeted_value, edit_budget_path(budget) %></td>
            <td>
            <% if budget.actual_value %>
                <%= link_to budget.actual_value, edit_budget_path(budget) %>
            <% else %>
                <%= link_to '+', edit_budget_path(budget) %>
            <% end %>
            </td>
            <% if budget.available(budget)>= 0 %>
                <td class="positive"><%= budget.available(budget) %></td>
            <% else %>
                <td class="negative"><%= budget.available(budget) %></td>
            <% end %>
            <td><%= link_to budget_path(budget), method: :delete do %>
                    <i class="fas fa-trash-alt"></i>
                <% end %>
            </td>
        </tr>
    <% end %>
</table>


<%= link_to 'New Budget', new_budget_path %>
<%= link_to 'New Category', new_category_path %>

app/views/budgets/new.html.erb
<%= render 'budgets/form'%>

app/views/categories/index.html.erb
<ul>
    <% @categories.each do |category| %>
        <li><%= category.category_name %></li>
    <% end %>
</ul>

app/views/categories/new.html.erb
<h3>Add a new category</h3>

<%= simple_form_for @category do |f| %>
  <%= f.input :category_name %>
  <%= f.button :submit %>
<% end %>

app/views/home/index.html.erb
<h2>Welcome, <%= current_user.email %></h2>

app/views/layouts/_navbar.html.erb
<header class="nav">
  <%= link_to 'BudgetApp', root_path, class: 'logo' %>
  <ul >
    <li><%= link_to 'Budgets', budgets_path, class: 'link link-theme link-arrow' %></li>
    <li><%= link_to 'Reports', '#', class: 'link link-theme link-arrow' %></li>
    <li><%= link_to 'My Page', edit_user_registration_path(current_user), class: 'link link-theme link-arrow' %></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2bf1586b4c.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= render 'layouts/navbar'%>
      <%= yield %>
    </div> 
  </body>
</html>